site_name: OMASLIB
site_url: https://omaslib.org
docs_dir: omaslib/docs
nav:
  - About: index.md
  - Introduction: introduction.md
  - LangString: langstring.md
  - PropertyClass: propertyclass.md

theme: readthedocs

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: sphinx
