site_name: OMASLIB
site_url: https://omaslib.org
docs_dir: docs
nav:
  - About: index.md
  - Introduction: introduction.md
  - Permission Concept: permission_concept.md
  - PropertyClass: propertyclass.md
  - Python Documentation:
      - Admin classes:
        - Project: python_docstrings/project.md
        - User: python_docstrings/user.md
        - UserDataclass class: python_docstrings/userdataclass.md
      - Data modeling:
        - Property class: python_docstrings/propertyclass.md
      - Helper:
        - XSD datatypes: python_docstrings/xsddatatypes.md
        - Context class: python_docstrings/context.md
        - Datatypes: python_docstrings/datatypes.md
        - Language enum: python_docstrings/language.md
        - OLDAP string literal: python_docstrings/oldap_string_literal
        - LangString class: python_docstrings/langstring.md
        - QueryProcessor class: python_docstrings/query_processor.md
        - InProject class: python_docstrings/in_project.md
        - Property attribute class: python_docstrings/propertyclassattr.md

theme: readthedocs

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: sphinx
