site_name: OMASLIB
site_url: https://omaslib.org
docs_dir: docs
nav:
  - About: index.md
  - Introduction: introduction.md
  - Permission Concept: permission_concept.md
  - PropertyClass: propertyclass.md
  - Python Documentation:
      - Datatypes: datatypes.md
      - Contex class: context.md
      - LangString class: langstring.md
      - UserDataclass class: userdataclass.md
      - User class: user.md

theme: readthedocs

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: sphinx
