site_name: OMASLIB
site_url: https://omaslib.org
docs_dir: docs
nav:
  - About: index.md
  - Introduction: introduction.md
  - Permission Concept: permission_concept.md
  - LangString: langstring.md
  - PropertyClass: propertyclass.md
  - Context: context.md
  - UserDataclass: userdataclass.md

theme: readthedocs

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: sphinx
