site_name: OMASLIB
site_url: https://omaslib.org
docs_dir: docs
nav:
  - About: index.md
  - Introduction: introduction.md
  - Permission Concept: permission_concept.md
  - PropertyClass: propertyclass.md
  - Python Documentation:
      - Language enum: python_docstrings/language.md
      - Datatypes: python_docstrings/datatypes.md
      - XSD datatypes: python_docstrings/xsddatatypes.md
      - Contex class: python_docstrings/context.md
      - LangString class: python_docstrings/langstring.md
      - Property class: python_docstrings/propertyclass.md
      - Property attribute class: python_docstrings/propertyclassattr.md
      - UserDataclass class: python_docstrings/userdataclass.md
      - User class: python_docstrings/user.md
      - Inproject class: python_docstrings/in_project.md

theme: readthedocs

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: sphinx
